- name: Baixando php composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
- name: Instalar o composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer
- name: Remoear composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
- name: Composer executável
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
- name: Criando link composer
  file:
    src: /usr/local/bin/composer
    dest: /usr/bin/composer
    state: link
- name: Altera a versão composer 
  shell: composer self-update 1.9.0 

- name: Setando chaves
  shell: composer config --global --global http-basic.repo.magento.com {{ api_user }} {{ api_pass }}
- name: setando permisssão do loja-blog1
  file:
    path: /var/www/html/loja1.segundorobtech.tk
    mode: '0755'

- name: Projeto Composer
  get_url:
    url: https://github.com/magento/magento2/archive/2.2.zip
    dest: /var/www/html/loja1.segundorobtech.tk

- name: Instalando Unzip
  yum:
    name: unzip
    state: present

- name: Descompactar magento2
  shell: >
    cd /var/www/html/loja1.segundorobtech.tk	 &&
    ls -la &&
    unzip -o magento2-2.2.zip &&
    cd magento2-2.2/bin &&
    chmod u+x magento

- name: Restart nginx
  service:
    name: nginx
    state: restarted
- name: Permissões blog1
  file:
    path: "/var/www/html/loja1.segundorobtech.tk"
    owner: nginx
    group: nginx
    recurse: yes

- name: executa composer install 
  shell: >
    cd /var/www/html/loja1.segundorobtech.tk/magento2-2.2 && composer install

- name: Instalando Magento
  shell: >
    cd /var/www/html/loja1.segundorobtech.tk/magento2-2.2/bin
    php bin/magento setup:install \
    --base-url=http://loja1.segundorobtech.tk \
    --base-url-secure=https://loja1.segundorobtech.tk \
    --use-secure=0 \
    --db-host=localhost \
    --db-name=magento \
    --db-user=magentouser \
    --db-password=admin123 \
    --admin-firstname=roberto \
    --admin-lastname=silva \
    --admin-email=robertosilvaseg0@gmail.com \
    --admin-user=admin \
    --admin-password=admin123 \
    --language=en_US \
    --currency=USD \
    --timezone=America/Chicago \
    --use-rewrites=1 \
    --backend-frontname="admin" \
    --use-sample-data
  args:
    chdir: /var/www/html/loja1.segundorobtech.tk

#- name: Recompilando Magento
  #shell: > 
    #cd /var/www/html/loja1.segundorobtech.tk/magento2-2.2 && # && php bin/magento setup:di:compile/html/loja1.segundorobtech.tk
- name: Permissões Magento
  shell: 
    cd /var/www/html/loja1.segundorobtech.tk/magento2-2.2
    find var vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod u+w {} \; && chmod u+x bin/magento
  args:
    chdir: /var/www/html/loja1.segundorobtech.tk

- name: Setando permissão
  file:
    path: "/var/www/html/loja1.segundorobtech.tk"
    owner: nginx
    group: nginx
    recurse: yes
    
- name: Arquivo conf da loja
  template:
    src: loja.conf.j2
    dest: /etc/nginx/conf.d/loja1.segundorobtech.tk.conf
- name: Restart php
  service:
    name: php-fpm
    state: restarted
- name: Restart nginx
  service:
    name: nginx
    state: restarted


